### ISSUE TITLE
Feature Request: "Raw gravitite" item and associated block?

### ISSUE THREAD

**Issue by muzikbike** [Gilded-Games/The-Aether#103]
Snapshot 21w14a changes ore drops such that no ore drops itself as an item when mined with unenchanted tools. As a result, gravitite would end up being an exception to this rule, and also remain the only ore unable to be multiplied via fortune. Not sure that gravitite ore should change to have a raw gravitite item that can be refined into enchanted gravitite and allow fortune compatibility, since that would be deviating from the old mod this plans to recreate, but it's something i'd recommend for vanilla continuity otherwise.

**Comment by raptor494** [comment]
It only does that because of the new ore variations with deepslate, since deepslate ore wouldn't stack with regular ore. Since the Aether has no equivalent to deepslate, this won't really be necessary.

**Comment by muzikbike** [comment]
So them adding it for compatibility with Fortune was a lie then?

**Comment by muzikbike** [comment]
https://www.minecraft.net/en-us/article/minecraft-snapshot-21w14a

the official blog post introducing them literally says "consistency with Fortune on all ores"...

**Comment by bconlon1** [comment]
@raptor494 we're not making decisions on anything 1.17 yet really. this is marked to be worried about figuring out later and it needs to be gone over with other devs

**Comment by bconlon1** [comment]
This has been discussed a bit and its been determined that trying to apply vanilla's design for raw ores doesn't really work for Gravitite Ore; vanilla designed it so that ore's that dropped blocks that smelted into items had an intermediary item now, but... that design doesn't really apply well with how Gravitite Ore is converted into a block, not an item, and is done so through enchanting. It doesn't make sense to go from block->item->block and also doesn't make sense to have a raw block as the intermediary if you consider fortune. Gravitite Ore's design will probably be left as is in Aether 1.
