### ISSUE TITLE
Bug: game freezes while using one core

### ISSUE THREAD

**Issue by TheAirBlow** [Gilded-Games/The-Aether#1358]
### What Feature Types Apply to This Bug?

Entity

### What Type of Bug Is This?

Crash

### Forge Version

14.23.5.2859 

### The Aether Version

1.5.3.2

### Is This Bug a Conflict With Another Mod?

No idea

### Client Log

https://mclo.gs/ZJe2QZO

### Crash Report (if applicable)

none

### Steps to Reproduce

It happens randomly while wandering in Aether

### What You Expect To Happen

For it to not freeze the game

### What Actually Happened

It fucking froze while using one core only

### Additional Details

Modpack is Divine Journey 2 (latest as of 16th may), version 1.12.2

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [ ] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by TheAirBlow** [comment]
Both me and my friend had it happen at least once, specifically in Aether

**Comment by Jonathing** [comment]
- This issue is reporting a problem with the 1.12.2 version of The Aether, a version that is no longer supported in favor of the 1.19.4 rewrite that has been taking place.
- There's simply so much going on in your log file, that it's hard to pinpoint the root cause of this issue. It is too much to ask the dev team to sift through your modpack logs and figure out a single thing that is causing their mod to potentially be breaking with the rest of them.
