### ISSUE TITLE
Feature Request: Bucket Tags

### ISSUE THREAD

**Issue by bconlon1** [Gilded-Games/The-Aether#1381]

**Comment by Jonathing** [comment]
Can you elaborate more on what this means? Buckets are like one of the most hard-coded features of the game.

**Comment by bconlon1** [comment]
We need a tag for milk buckets to hold Skyroot Milk Buckets and Milk Buckets, and maybe a tag for Skyroot Water Buckets and Water Buckets in case it might be necessary but I haven't thought of any crafting situations where it would be.

**Comment by Jonathing** [comment]
Yikes. This is something that could probably easily be added into the mod itself, but I'm worried about compat with other mods. I don't know if our friends at Forge would be so willing to help us out with that (meaning, our PRs might get yeeted into the void for such a niche use case). Let me know what you think here or in chat since I might be personally invested for the sake of mod compatibility.
