### ISSUE TITLE
Feature Request: Stackable Life Shards

### ISSUE THREAD

**Issue by DeadlyFource** [Gilded-Games/The-Aether#1383]
### What Feature Types Apply to This Request?

Item

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

As title states.

### Why Should It Be in the Mod?

Makes it easier to loot them from a chest if one's inventory is cluttered, and easier to use overall as well.

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
We don't plan to make Life Shards stackable, since the point is to use them, they shouldn't be much of a clutter issue, and considering their rarity and time between obtaining, the average player is going to only have one or two at a time so stacking doesn't make them any easier to use. They also weren't stackable in the original versions of the mod and we would like to keep parity with that.
