### ISSUE TITLE
Bug: When typing at an other's mod GUI things: G, I it opens the mod window

### ISSUE THREAD

**Issue by michelle1574** [Gilded-Games/The-Aether#1838]
### What Feature Types Apply to This Bug?

Other (Please Describe)

### Other Type

Typing

### What Type of Bug Is This?

Annoyance

### Forge Version

43.3.5

### The Aether Version

1.0.0-beta3

### Is This Bug a Conflict With Another Mod?

Public Transport Mod

### Steps to Reproduce

1. Use a house number sign
2. When an GUI opens, type a word that contains G or I

### What You Expect To Happen

It would type normally.

### What Actually Happened

An Aether-related GUI opened causing the other GUI to close.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by OzPayn** [comment]
Given that the Curios keybind is also triggering an inventory open during typing, I think this is more an issue with how Public Transport Mod handles its text GUI rather than a problem with the Aether's keybinds. I would recommend reporting it to them instead.

Closing this issue as it isn't specific to the Aether's implementation. If it turns out the compatibility issue can be solved by some change in implementation on our end rather than theirs then another issue can be opened.
