### ISSUE TITLE
Bug: Vorbis aether#.ogg files are horribly low quality

### ISSUE THREAD

**Issue by jadenquinn** [Gilded-Games/The-Aether#1847]
### What Feature Types Apply to This Bug?

Audio

### What Type of Bug Is This?

Annoyance

### Forge Version

N/A

### The Aether Version

N/A - 1.20.x

### Is This Bug a Conflict With Another Mod?

No.

### Client Log

N/A.

### Steps to Reproduce

Download this mod.
Extract the jar file as if it was a zip file.
Try to get the music from within for your listening pleasure.
Get mad that it's even LESS quality than in the original mod... somehow!

### What You Expect To Happen

Rest of details are in Additional Details below.

### What Actually Happened

Rest of details are in Additional Details below.

### Additional Details

I have the lossless versions of these songs. Is this a licensing issue or something? I don't know or understand why the bitrate/quality of aether1.ogg, aether2.ogg, aether3.ogg, aether4.ogg, and aether5.ogg are so horrid. Even the original mod from 2011 included these tracks at at least twice audible quality, and this is in a world where the lossless versions aren't that hard to get, and a much, MUCH higher (indistinguishable from lossless) quality mix can easily be made using the Opus codec (which is very similar apparently to Ogg Vorbis) or other modern codecs, even a higher bitrate and preset with Ogg Vorbis would yield a much better result. What files were you guys even transcoding from? How did this even happen? Who is responsible for this?

Yes I just basically had a fit in here about something that no one actually cares about, I just can't imagine this wasn't very easily solvable, just no one decided to put in the effort... yet. If you need the files, I have em, I just really don't know how to use Github properly so I am... afraid... of doing anything more than this on my own, sorry.

(About the check boxes below this text box)
No idea if this has been reported already, didn't care to look, nothing to do with Optifine, nothing to do with the version of Minecraft, ...this included a lot of random points I think but whatever, nothing to do with a modpack. K? K.

Thanks,
-j

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by jadenquinn** [comment]
Update: The lossless audio track files are available on Bandcamp, I don't think I even had to pay, and by the fact that it says the person made it for the Aether mod specifically, I'm sure they'd be willing to let you guys add a compressed version into this updated/up-ported mod.. yes I forgot the word for "up-porting". It's 2am, forgive me.

Sorry if this post was really messy, It's 2am like I said, and if I waited, I wouldn't have remembered to post at all soooo yea.

**Comment by OzPayn** [comment]
I'll make sure we look into this again but afaik the current bitrate/quality was the best compromise we could come to without massively inflating the filesize of the mod. I'm not an audio engineer so I'm not particularly well equipped to make judgement calls on this but you can see some of the decision making from this issue here: [https://github.com/The-Aether-Team/The-Aether/issues/1095](https://github.com/The-Aether-Team/The-Aether/issues/1095)

Originally in this rewrite we used the files from the original release but they are significantly larger than what I think could be expected to be reasonable for a minecraft mod, so a compressed set was included to reduce the file size. iirc some discussion has been made since around ways to improve audio quality while keeping the file sizes in check but I'm not certain any hard conclusions were made there.

So yeah basically the current audio is matching the 1.7-1.12 Aether Legacy releases, which afaik any audio work would have been done by the Modding Legacy team. I'm open to suggestions for improving the audio quality but yeah it needs to not contribute to an inflation of the mod's file size.

**Comment by OzPayn** [comment]
Basically - yeah its a compromise, I'm open to re-evaluating said compromise, but file size is the primary concern

**Comment by bconlon1** [comment]
Most of the current compressed music files were done by the Modding Legacy team using our original music files by Emile from the original mod. Using the non-compressed files for the mod essentially doubles the file size, which we want to avoid. No changes have been made to the files as we have not gotten any complaints about the in-game quality from players, so the current compromise between quality and file size has seemed good. For out-of-game quality, that's what getting them directly from Emile's Bandcamp is for (we should probably get around to linking to that from somewhere official at some point). Since the repository is open source though, anyone is free to contribute changes if they manage to create compressed files with better quality while still retaining low size.
