### ISSUE TITLE
Feature Request: automatically use Curios slots if curios is present

### ISSUE THREAD

**Issue by shimmer-n-shine** [Gilded-Games/The-Aether#1894]
### What Feature Types Apply to This Request?

Config, System

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

The mod should be able to detect if Curios is present and replace the aether's own slots with it by default. It might be easier to reframe the configuration as "force aether slots" instead of "use aether slots" to facilitate the auto-configuration of the mod to use curios slots.

### Why Should It Be in the Mod?

The presence of a framework mod like lootr or curios should enable integration with them by default, instead of it being an opt-in setting within the Aether's configuration. 

### Does This Feature Improve Compatibility With Another Mod?

Curios

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by OzPayn** [comment]
The mod is dependent on and bundles in Curios, I think there is valid debate over which configuration should be the default but the option is already there and I don't think the presence of a curios installation would be a good way of deciding that configuration given the mod doesn't run without it

**Comment by shimmer-n-shine** [comment]
Oh, I wasn't aware that Curios was a prerequisite. Then I understand why the team wants to include the aether's own slots because it's your own implementation and because of nostalgia, but by default mod compatibility really should be prioritised over a mod's own features. 

With 1.20.1 no longer having a working version of [Configured](https://github.com/MrCrayfish/Configured), it adds an extra layer of technical hurdle for users who might not be tech-savvy but with the ease of use of modern modding tools can put together their own mod packs and modded instances. 

Would it then be possible to use Reflection to retrieve if other mods have registered curios slots and to use that as a basis for automatic configuration?

**Comment by OzPayn** [comment]
I disagree that a compatibility result should be the default, the default should be the expected outcome of a user wanting the features of the mod, beyond that expectation that is precisely why config options exist. If we can't rely on users being able to configure their mods then the whole thing is sort of pointless.

The default for Aether 1 is always going to be what best reflects the original content and intent of the mod, but we offer a range of configuration options, a very standard practise, to allow for customisation and compatibility. If a player isn't aware of configs then realistically they're not going to be making their own modlist anyway I feel. I do not think it warrants extra invisible compatibility changes, changes from default should be player driven.

**Comment by shimmer-n-shine** [comment]
While I agree with you, Forge has regressed in the past few years in ease of configurability for players, while minecraft modding as a whole has advanced in accessibility for players. This has resulted in config files to be more or less "advanced" as the tools that allowed easy configuration before (the mod config option in the Mods screen or example) are not available any more, or mods that brought these features to new versions are also no longer available.

In addition to this, as minecraft's modding API has matured, there's been a push towards silent compatibility. It has been standard for mods for years to configure themselves automatically and silently to be compatible with other mods. The aether should not be an exception to this. I understand that the Aether mod reflects the original intent and content of the original mod, However, it's a port now existing on 1.19 and 1.20, so it should be expected to follow modern modding standards.

**Comment by OzPayn** [comment]
Silent compatibility is one thing, changing features that don't affect compatibility for the sake of organisation or preference is another. The default inventory slots are fully compatible with other curios implementations (because it is curios still) its just in a different GUI. If people prefer to not have that, the option is there, but I do not think switching it by default if other curios enabled mods are present is a good implementation, it assumes a preference.
I'm all for increased compatibility by default when we can, but in this case it really is more of a visual feature than a functional one, so I'd prefer to keep the Aether's original inventory styling by default.

I agree that configuration is (bizarrely) much harder these days because of the lack of a mod settings menu by default, but I do not think that reflects an inability for general users to use config options, and even if they cannot, the default implementation still works completely fine.

I'd like to hear bcon's opinion on this though so I'll keep the issue open until we hear from them. It's an interesting design question that I do think there's wiggle room on.

**Comment by slottwo** [comment]
Ignoring the "automatic" part, is there still this configuration to use Curios? I don't find anywhere in the archives.
