### ISSUE TITLE
Bug: Breaking the Block underneath and berrybush doesn´t drop the stem

### ISSUE THREAD

**Issue by Builderdog841** [Gilded-Games/The-Aether#193]

**Comment by bconlon1** [comment]
Might need help figuring this one out. I'm not sure how to handle the loot table situation for if the blueberry bush is broken not by hand but from the block beneath it being removed.

**Comment by bconlon1** [comment]
Have attempted to make a loot table solution to this but I worry it may have unexpected cases where it either does or doesn't work. May look into a way of making it so that whenever a berry bush is destroyed it'll destroy the bush, convert to the stem, then also break the stem, that way it'll always drop both.
