### ISSUE TITLE
Mod licensing makes it illegal to actually play the mod

### ISSUE THREAD

**Issue by strugee** [Gilded-Games/The-Aether#199]
https://github.com/Gilded-Games/The-Aether/blob/492f2afa06dcd3d13711a98724a7c64ad45275af/README.md#scroll-license-information says that everything in the `resources/` directory is "all rights reserved". This includes the right to actually play the mod using these resources, because there is not a specific grant of that right to players. Due to this issue, anyone actually playing the mod is violating copyright law.

**Comment by strugee** [comment]
Additionally, those licensing terms seem to conflict with https://github.com/Gilded-Games/The-Aether/blob/1.16/CONTRIBUTING.md#contributor-license-agreement.

**Comment by bconlon1** [comment]
The assets in this mod are considered "Older assets in the Aether project", so there is not necessarily a conflict in the contributing agreement. However, improving the phrasing should probably be looked into (this contributing document has been carried over from the other Aether repositories, so it could probably be better phrased to fit this one specifically). As for the issue with the usage of All Rights Reserved in the first place, I will have to look into that.

**Comment by bconlon1** [comment]
After looking into this further, this seems like a nonissue. As far as I understand, since All Rights Reserved is the copyright for our assets, this only affects the copying/distribution of our assets; this copyright does not affect the right for the players to consume/play the mod. Even if it did, we still normally distribute the mod through CurseForge, a platform made to let players download and play mods, so I believe that well implies the players have the right to play the mod. Even though the content of this repository is not yet technically on CurseForge, this reasoning still applies to CircleCI, as we had to specifically setup the builds on that service, and the intention of its usage is for the builds to be downloaded and tested through playing.

As for the conflicting licensing terms, I will have to go over a rephrasing of the CONTRIBUTING.md file at some point anyways due to unclear plans going forward of what to do with this repository's asset licensing once we implement the retexture to the mod, but as of now the file's phrasing applies correctly to this repository and any rephrasing of it can be handled later on when changes need to be made to it for the previously stated reasons.

**Comment by strugee** [comment]
> As far as I understand, since All Rights Reserved is the copyright for our assets, this only affects the copying/distribution of our assets; this copyright does not affect the right for the players to consume/play the mod. Even if it did, we still normally distribute the mod through CurseForge, a platform made to let players download and play mods, so I believe that well implies the players have the right to play the mod.

That's not correct, "All Rights Reserved" means _all_ rights, including the right to play with the asset in-game. However, you're right that CurseForge's Terms of Service probably grant this right, although I haven't actually checked. I can PR a clarifying note to that effect if you want.

You may find https://choosealicense.com/no-permission/ helpful in understanding how the "All Rights Reserved" license (which is always implied when you don't have a license, but explicit here) affects usage of the assets.

**Comment by TelepathicGrunt** [comment]
@strugee ARR means all rights reserved yes, but when we modders post to curseforge, we are *explicitly* granting the right of redistributing the mods to Overwolf because that is part of the ToS. Users can download the mods from curseforge AND play the mods legally. ARR does not prohibit that. 

If ARR was as locked down as you say it is, no ARR software can ever be used. Except they can and that is because ARR does not apply to consuming the media. Playing an ARR mod is legal. ARR and other licenses for software are more about redistributing or modifying the software. But even then, there are many holes through ARR such as reverse engineering an ARR software to fix a bug or do compatibility is legal in many countries so ARR cannot protect from that either. 

If you are still confused, I would suggest reaching out to a lawyer for software to help clarify it for you.

For now, you can take a look at the terms we modders agreed to when posting on curseforge here: 
https://overwolf.github.io/docs/topics/legal-developers-terms
Specifically, 5.ii. is what you'll want to look at.

**Comment by RobertCochran** [comment]
I'm going to point out a related-but-separate-issue: you've made it illegal to copy the repository in its entirety, which will probably surprise folks that see the "LGPL-3.0 License" and assume life is okay from there... that's setting people up for failure and I'd consider it to be 'rude' at best.

**Comment by TelepathicGrunt** [comment]
@RobertCochran The code is LGPLv3. The assets is ARR. People can fork and modify the code portion of the mod but cannot modify or redistribute the assets. This is a very common and legal way to do licensing. So no, it is not illegal to copy the entire repo. It’s illegal to take the assets and reuse it elsewhere. THAT’S what is illegal. Anyone can still fork this repo, make code changes, and PR it back to the original repo.

Sorry if I am sounding a bit short but while licenses can be confusing, this case of open source code and arr assets really is causing no problems at all. Please talk to a lawyer dedicated to software licensing if you do not believe me and what other modders and even giant software companies are doing.

**Comment by reetamb** [comment]
I see the license's purpose of making clear what is and isn't allowed has been going smoothly.

**Comment by bconlon1** [comment]
I personally would not consider trying to protect our assets from theft like has occurred in the past rude, while still trying to maintain our code as open source so those who want to contribute to the project have the ability to. I think TelepathicGrunt has explained here best why there are no issues with the Aether's choice of licensing, which have been made to maintain these two purposes. Although I can add to TelepathicGrunt's explanation that GitHub's TOS also permits forking any published repositories, so the repository is definitely not illegal to copy (at least if kept here within GitHub).

**Comment by strugee** [comment]
Hi @TelepathicGrunt, thanks for your response. I've been thinking for a few days about how I want to respond because while I believe that you have some misconceptions on how copyright works, I am not a lawyer and I certainly could be wrong. I'm trying to cite sources as to why I believe that, while not writing too much and being totally boring. I really hope that I've at least somewhat succeeded 😅 

I appreciate the link to the Overwolf terms of service and we are definitely in agreement that section 5.ii. permits redistribution (at least on CurseForge). However, this point:

> If ARR was as locked down as you say it is, no ARR software can ever be used.

isn't quite right. Copyrighted software is locked down in this way _by default_ - that is, nobody but the copyright holder is allowed to run the software - but the copyright holder can grant licenses to other people that allow them to run the software. For example, the [EULA that comes with macOS](https://www.apple.com/legal/sla/docs/macOSBigSur.pdf) grants you the right to run the software in various specific circumstances in section 2. Take section 2.A. for example:

> Subject to the terms and conditions of this License, unless you obtained the Apple Software from the Mac App Store, through an automatic download or under a volume license, maintenance or other written agreement from Apple, you are granted a limited, non-exclusive license to install, use and run one (1) copy of the Apple Software on a single Apple-branded computer at any one time. For example, these single-copy license terms apply to you if you obtained the Apple Software preinstalled on Apple-branded hardware.

Notice how it grants the right to "run...the Apple Software" and specifies the terms for that right. You will find the same in any open source license, as these licenses are also built on copyright. For example, [the MIT license](https://choosealicense.com/licenses/mit/) grants users the right to "use...copies of the Software". Indeed, the freedom to use a program without restriction is freedom 0 in the [Free Software Definition](https://www.gnu.org/philosophy/free-sw.html). Consider that these clauses in licenses, and freedom 0 in the Free Software Definition, would not have to exist if everyone unambiguously had the right to run software they got a copy of.

> But even then, there are many holes through ARR such as reverse engineering an ARR software to fix a bug or do compatibility is legal in many countries so ARR cannot protect from that either.

As a final thought, I would seriously advise you to be cautious with this line of thinking. While things are starting to change for the better such that these kinds of activities are becoming less restricted, what you are allowed to do to a proprietary binary is legally murky and "reverse engineering software to fix a bug" may be a violation of copyright law that can get you into serious legal trouble. This is _especially_ true if the company has abused the DMCA's anti-circumvention clause to make this extra illegal, [which companies do on a regular basis](https://www.eff.org/deeplinks/2014/09/eff-congress-get-rid-dmcas-anti-circumvention-provisions). See the [EFF's FAQ on this subject](https://www.eff.org/issues/coders/reverse-engineering-faq).

This is very dangerous advice. In the worst case, [you can go to jail and be fined hundreds of thousands of dollars](https://www.copyright.gov/title17/92chap12.html#1204) for violating the DMCA's anti-circumvention clause.
