### ISSUE TITLE
Bug: <Quick Load Crash with Leawind's Third Person Mod>

### ISSUE THREAD

**Issue by AmazeingGames** [Gilded-Games/The-Aether#2081]
### What Feature Types Apply to This Bug?

System, Other (Please Describe)

### Other Type

Main Menu Quick Load

### What Type of Bug Is This?

Crash

### Forge Version

43.3.0

### The Aether Version

1.3.1

### Is This Bug a Conflict With Another Mod?

[leawind_third_person-v2.0.7-mc1.19.2-forge](https://www.curseforge.com/minecraft/mc-mods/leawind-third-person/files/5161608)

### Crash Report (if applicable)

https://gist.github.com/AmazeingGames/58d2ea1f6813176f8c0a224cbdd6d43d

### Steps to Reproduce

From my testing this happened without fail when the given mod is loaded alongside the Aether.

1. Launch Minecraft
2. World begins to load in
-- Game Crashes --
1.1. If game has not crashed, hit 'Toggle World' in the top right
-- Game Crashes --

### What You Expect To Happen

The 'quick world' feature should load and display properly.

### What Actually Happened

The game crashes and I'm hit with a crash report.

### Additional Details

Game version is 19.2. Other than the needed mods being Architecture, Leawind's Third Person, and The Aether my mod folder was completely empty.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
This seems to be an issue stemming from here: https://github.com/LEAWIND/Third-Person/blob/d3ada67a4fa4155a6eff4e389551dc44d4a5e18f/common/src/main/java/net/leawind/mc/thirdperson/impl/core/EntityAgentImpl.java#L189. I can only assume the issue is that the camera entity doesn't exist during the timeframe that the world preview loads the world and the third person mod needs the camera. You could report it there to have them add a null check, but otherwise I think I can only recommend just not using the world preview since I'm not sure if there's anything I could do on Aether's end to get around that.

**Comment by AmazeingGames** [comment]
Thank you; I will post a report there along with the the information you sent!
