### ISSUE TITLE
Eternal day is actually an eternal night

### ISSUE THREAD

**Issue by BriceFable** [Gilded-Games/The-Aether#2217]
### What Feature Types Apply to This Bug?

Other (Please Describe)

### Other Type

Day-Night Cycle

### What Type of Bug Is This?

Compatibility

### Forge Version

47.3.0

### The Aether Version

1.4.2

### Is This Bug a Conflict With Another Mod?

Cobblemon

### Client Log

Not required

### Crash Report (if applicable)

Not required

### Steps to Reproduce

Step 1: Enter world
Step 2: Make Aether portal and enter it
Step 3: Check time of day
![report](https://github.com/The-Aether-Team/The-Aether/assets/64082541/60aab194-715c-46c2-9635-adc72aa79ad7)

### What You Expect To Happen

I expected the time of day to be stuck in an eternal day until the Sun Spirit boss was defeated.

### What Actually Happened

The time of day is actually an eternal fullbright night (15:00).

### Additional Details

While not a very big issue to anyone that doesn't need to worry about daytime, for Cobblemon that has strict day and night requirements for its spawns, being stuck in an eternal night in broad daylight messes up spawns and can be very confusing to players.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by bconlon1** [comment]
This seems to be caused by Cobblemon (and probably JourneyMap) basing day/night checks off of world time ticks, and the Aether has a greater number of these that make up its day/night periods (72000 as opposed to 24000). I don't think there's anything we could do on our end to get around this, but this bug could be reported to them and they might have ideas for how to work with it. It might be possible for them to use `getTimeOfDay()` which is dependent on the dimension and I believe gives a decimal scale for the time of day, which should be the same between the Overworld and the Aether.
