### ISSUE TITLE
Feature: Rankings System

### ISSUE THREAD

**Issue by Jaryt** [Gilded-Games/The-Aether#228]
- Perks: Dev Glow, Dev Halo
- Perks and Customization Screen: Acts as a configuration menu for various things. Various buttons will only appear if the player has access to certain perks. Gloves Toggle can be used to switch between the skin and hat layer for first person glove rendering. Dev Glow and Dev Halo Toggle can disable and enable their rendering. Color Code Inputs will exist for the Dev Glow and Dev Halo to change what color they are. This screen will also allow access to the Patreon Rewards configuration screen.

**Comment by bconlon1** [comment]
Content from branch `feature/rankings_system` needs to be ported.
- [x] PlayerHaloModel
- [x] PlayerHaloLayer
- [x] DeveloperGlowLayer
- [x] client.renderer.perk package.
- [x] PlayerRanking
- [x] AetherPlayerRankings
- [x] AetherRankings
- [x] IAetherRankings
- [x] RankingEvent
- [x] AetherRankingsListener
- [x] CustomizationScreen
- [x] Button for CustomizationScreen
- [x] Behavior to toggle between arm and sleeve layer for Gloves in first person (should probably use EntityDataManager now instead of packets).
