### ISSUE TITLE
Feature Request: remove accessories as embedded library

### ISSUE THREAD

**Issue by VaporeonScripts** [Gilded-Games/The-Aether#2376]
### What Feature Types Apply to This Request?

Other (Please Describe)

### Other Type

remove dependency as not not needed 

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

remove accessories embedded dependency, as most people dont use it/got curios continuation

### Why Should It Be in the Mod?

should be removed

### Does This Feature Improve Compatibility With Another Mod?

well kinda

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
The dependency isn't "not needed" since it is what our accessories implementation currently depends on, it can't just be removed on its own. The Accessories API was used since it makes the handling of our Fabric port's development alongside the NeoForge version much smoother, and the API should still be compatible with other mods especially if they've maintained Curios' data-driven customization for managing slots. The API was also used before a reliable Curios successor popped up, although that whole situation has at least given me concerns about future-proofing in the vein of this request, as detailed in #2194, since while I don't expect Accessories API to disappear any time soon I would like to have the mod be prepared for anything (this however is still quite low priority compared to other develpment tasks).
