### ISSUE TITLE
Parts of the world are invisible when Rubidium is installed

### ISSUE THREAD

**Issue by DynexTheSergal** [Gilded-Games/The-Aether#937]
### What Feature Types Apply to This Bug?

Block

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

1.19.2-43.2.3

### The Aether Version

aether-1.19.2-0.2.0

### Is This Bug a Conflict With Another Mod?

Rubidium-0.6.2

### Steps to Reproduce

Create a World look around and look for invisible.. er missing blocks and can also see caves through the world

### What You Expect To Happen

All blocks to be not invisible and or glitched

### What Actually Happened

Able to see through the world in certain areas. Perhaps objects aren't rendering properly maybe that's why they are invisible 

### Additional Details

no other mods just Aether, Curios and Rubidium

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
Sounds like a Rubidium issue: https://github.com/Asek3/Rubidium/issues/183

**Comment by bipsydev** [comment]
This is fixed in MC 1.19.2 with [Rubidium's PR #448](https://github.com/Asek3/Rubidium/pull/448), although this bug does reoccur in MC 1.19.4 with the latest 0.6.4 release of Rubidium. [This PR #475 (thanks bconlon1)](https://github.com/Asek3/Rubidium/pull/475) fixes it but it's still not in the latest release.

In the meantime in case anyone else finds this and is in dire need of this fix on 1.19.4, [here's a current dev build of Rubidium including that PR](https://drive.google.com/file/d/1Y2rUojTOgOq2gWL0T2fsgqRGLuzw89Si/view?usp=sharing) I made just for you! Not sure if the fix is included in the latest 1.19.2 release but it's easy to clone the recent dev branch and make your own build if you need that.
